export const SCREENS = {
  HOME:'Home',
  DASHBOARD: "Dashboard",
  SEARCH: "Search",
  NOTIFICATION: "Notification",
  PROFILE: "Profile",
  DETAIL: "Detail",
  LOGIN: "Login",
  TAB: "Tab",
  SIGNUP:"Signup",
  SIGNIN:'SignIn',
  MAIN:'Main',
  MAINSTACK:'MainStack',
  MESSAGE:'Message',
  VISIT:'Visit',
  ENQUIRY:'Enquiry',
  CMS:'CMS',
  PRODUCTCATALOUGE:'ProductCatalouge',
  MOREOPTIONS:'MoreOptions',
  SETTING:'Setting',
  CREATE_VISIT_PLAN:'Create_Visit_Plan',
  CREATE_CUSTOMER_VIEW_MODEL:'Create_Customer_View_Model',
  CREATE_MEETING_DETAILS:'Create_Meeting_Details',
  VIEW_CUSTOMER_PROFILE:'View_Customer_Profile'

};
