//#region Account
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_APP_THEME = "SET_APP_THEME";
export const DESTROY_SESSION = "DESTROY_SESSION";
export const VISIT_TYPE= "VISIT_TYPE";
export const ENQUIRY_TYPE= "ENQUIRY_TYPE";
export const MODAL_TYPE="MODAL_TYPE";
export const TAB_TYPE="TAB_TYPE";
export const COMPEITITOR_BUTTON_TYPE="COMPEITITOR_BUTTON_TYPE";
export const PROFILE_BUTTON_TYPE="PROFILE_BUTTON_TYPE";
export const SIGNUP='SIGNUP';
export const SET_LOADER_VISIBLE ='SET_LOADER_VISIBLE';
export const UPDATED_BASE_URL="UPDATED_BASE_URL";
export const UPDATE_USER_DATA="UPDATE_USER_DATA";
export const SET_CMS_PAGE="SET_CMS_PAGE";
export const SET_DASHBOARD_DATA="SET_DASHBOARD_DATA";
export const SET_DEVICE_TOKEN="SET_DEVICE_TOKEN";
export const SET_UPCOMING_VISITS = "SET_UPCOMING_VISITS";
export const SET_PLANNED_VISITS = "SET_PLANNED_VISITS";
export const SET_EXECUTED_VISITS = "SET_EXECUTED_VISITS";
export const SET_MESSAGE_DATA = "SET_MESSAGE_DATA";
export const SET_ESCALATED_DATA = "SET_ESCALATED_DATA";
export const SET_NOTIFICATION_DATA="SET_NOTIFICATION_DATA";
export const SET_MASTER_DATA="SET_MASTER_DATA";

