import { WindowWidth } from "libs";
import React from "react";
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
   openIssue:{
      fontWeight: "500",
      fontSize: 14,
      lineHeight: 14,
      alignSelf:'center',
      color: "#233972",
    },
    resolvedIssue:{
      fontWeight: "500",
      fontSize: 14,
      lineHeight: 14,
      color: "#00000080",
    },
    line:{
      height: 3,
      width: WindowWidth/2,
      backgroundColor: "#233972",
      marginTop: 16,
    },
  TextInput: {
    height: 56,
    width: "100%",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 16,
    borderRadius: 33,
    marginTop: 16,
  },
  location: {
    height: 56,
    width: "100%",
    marginTop: 12,
    backgroundColor: "#FFFFFF",
    borderRadius: 33,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
  },
  searchbtn: {
    height: 56,
    width: '100%',
    marginTop: 16,
    backgroundColor: "#DFDEE1",
    borderRadius: 33,
    flexDirection: "row",
    justifyContent:'center',
    alignItems:'center',
  },
  searchbtns: {
    height: 56,
    width: '100%',
    marginTop: 16,
    backgroundColor: "#FFFFFF",
    borderRadius: 33,
    borderWidth: 1,
    borderColor: "#233972",
    flexDirection: "row",
    justifyContent:'center',
    alignItems:'center',
  },
  nameNotFocus: {
    color: "#110F24",
    fontWeight: "400",
    fontSize: 14,
    lineHeight: 15,
  },
  nameFocus: {
    color: "#110F24",
    fontWeight: "400",
    fontSize: 14,
    lineHeight: 15,
    position: "absolute",
    top: 25,
    left: 26,
  },
  nameContainer: {
    color: "#110F2480",
    position: "absolute",
    top: 9,
    left: 27,
    fontWeight: "400",
    fontSize: 12,
    height: 15,
    lineHeight: 12,
  },
  locationDropDown: {
    color: "#110F2480",
    position: "absolute",
    top: 9,
    left: 24,
    fontWeight: "400",
    fontSize: 12,
    lineHeight: 12,
    height: 15,
  },
  locationNotFocusText: {
    height: 18,
    fontWeight: "400",
    fontSize: 14,
    lineHeight: 17.5,
  },
  locationFocusText: {
    height: 18,
    fontWeight: "400",
    color: "#110F24",
    fontSize: 14,
    marginLeft: 9,
    lineHeight: 17.5,
    marginTop: 5,
  },
  arrow: {
    tintColor: "#110F2480",
    transform: [{ rotate: "90deg" }],
  },
  locationList:{
   marginHorizontal: 20,
   backgroundColor: "#FFFFFF",
   marginTop: 5,
   padding:5,
   // borderRadius: 20,
 },
 searchBtnTxtNotFocus:{
   color: "#110F2480",
   height: 18,
   fontWeight: "500",
   fontSize: 14,
   lineHeight: 17.5,
 },
 searchBtnTxtFocus:{
   color: "#233972",
   height: 18,
   fontWeight: "500",
   fontSize: 14,
   lineHeight: 17.5,
 }
});
export default styles;
